# Site settings
title: Parth Krishna
description: My portfolio website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: ""
url: https://thenerdsuperuser.xyz

# User settings
username: Parth Krishna
user_description: I am CS grad, tinkering with any and every kind of technology. Do read my notes to see how random I can be at times. I am planning to use the JAM Stack. later ~~!
user_title: Software Developer
email: thenerdsuperuser@gmail.com
twitter_username: vimoveremacs
linkedin_username: parthkrishna
github_username:  thenerdsuperuser
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
